Use static toString directly
This will fix the following warning (treated as error) from MSVC
compilers:

```
sqsrequest.cpp(112): error C2220: warning treated as error - no 'object' file generated
sqsrequest.cpp(112): warning C4189: 'd': local variable is initialized but not reference
```

Because, of course, the d-ptr get's optimised out entirely.